export interface typeDataSource {
        key: number,
        active_flg: number,
        parent_unit_name: string | null,
        unit_qty: number,
        price: number,
        inv_qty_alarm: number,
        drug_unit_id: number,
        drug_id: number,
        unit_id: number,
        unit_name: string,
        parent_unit: string,
        status: number,
        max_price: number,
        drug_price_id: number,
        price_before_vat: number,
        wholesale_price: number,
        wholesale_price_before_vat: number,
        default_flg: number,
}


export interface typeDataAll {
        prefix: string,
        unit_name: string,
        account_id: number,
        active_flg: number,
        active_ingredient: string,
        administration: string,
        adverse_reaction: string,
        atc_code: string,
        avatar_url: string,
        barcode_url: string,
        company_code: string,
        company_name: string,
        concentration: string,
        contraindication: string,
        country: string,
        created_date: string,
        description: string,
        direction_for_use: string,
        dosage: string,
        drg_barcode: string,
        drg_drug_alias: string,
        drg_drug_cd: string,
        drg_drug_name: string,
        drg_ref_cd: string,
        drg_store_id: number,
        drug_classified: string,
        drug_flg: null,
        drug_group: string,
        drug_id: number,
        drug_kind: string,
        drug_units: DrgUnitsModel[]
        employee_commissions: number,
        end_date: null,
        image_number: number,
        image_url: string,
        indication: string,
        interation: string,
        license_cd: string,
        loyalty_flg: number,
        moisture: string,
        note: string,
        original_product: string,
        overdosage: string,
        package_desc: string,
        precaution: string,
        provider_code: string,
        provider_name: string,
        ref_code: string,
        revision: number,
        source: string,
        special_control: string,
        start_date: string,
        status: 1
        storage_temperature: string,
        updated_date: null
        updated_user: string,
        vat_percent: number,
}

export interface DrgUnitsModel {
    active_flg: number,
    default_flg: number,
    drug_id: number,
    drug_price_id: number,
    drug_unit_id: number,
    inv_qty_alarm: number,
    max_price: number,
    parent_unit: string,
    parent_unit_name: null,
    price: number,
    price_before_vat: number,
    unit_id: number,
    unit_name: string,
    unit_qty: number,
    wholesale_price: number,
    wholesale_price_before_vat: number,
}